services:
  db:
    image: mysql:8.4.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: OunDeDeDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    restart: unless-stopped
    networks:
      - app-network

  srv:
    image: dacnguyen9101/oun-de-de:$IMAGE_TAG
    depends_on:
      - db
    environment:
      GIT_SHA: $GIT_SHA
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:1.24.0
    ports:
      - "80:80"
    depends_on:
      - srv
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network