server:
  forward-headers-strategy: framework
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    loggers: slf4j
    baseline-on-migrate: true
  application:
    name: oun-de-de
  datasource:
    url: ${DB_URL}
    username: ${DB_USRNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCorePool
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 300000    # 5 minutes
      max-lifetime: 480000   # 6 minutes
      keepalive-time: 300000  # 5 minutes
      auto-commit: true
      connection-timeout: 30000   # 30s max wait
      connection-test-query: select * from information_schema.tables limit 1

  jpa:
    hibernate:
      ddl-auto: none
    #      DO NOT USE IN PRODUCTION
    #      ddl-auto: create-drop
    #      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  main:
    allow-bean-definition-overriding: true

security:
  jwt:
    secret: ${JWT_SECRET:}
    expiration: 3600s
    refreshExpiration: 86400s # 1day

logging:
  level:
    com.cdtphuhoi.oun_de_de: DEBUG
    org.flywaydb.core: DEBUG
#    root: trace

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  paths-to-match: /api/v1/**/, /health
  show-actuator: true

cors-config:
  properties:
    allowed-origins: https://cdtphuhoi.com,http://cdtphuhoi.com
    allowed-methods: "*"
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600