spring:
  application:
    name: oun-de-de
  datasource:
    url: ${DB_URL}
    username: ${DB_USRNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
#      DO NOT USE IN PRODUCTION
#      ddl-auto: create-drop
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  main:
    allow-bean-definition-overriding: true

security:
  jwt:
    secret: ${JWT_SECRET:}
    expiration: 3600s
    refreshExpiration: 86400s # 1day

logging:
  level:
    ccom.cdtphuhoi.oun_de_de: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  paths-to-match: /api/v1/**/, /health
  show-actuator: true

cors-config:
  properties:
    allowed-origins: "cdtphuhoi.com"
    allowed-methods: "*"
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600
