services:
  db:
    image: mysql:8.4.7
    environment:
      MYSQL_ROOT_PASSWORD: dac
      MYSQL_DATABASE: OunDeDeDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql

  srv:
    image: dacnguyen9101/oun-de-de:dev-3f4371014ccb4e99f6db8b86e7fd6afcac0f80c9
    depends_on:
      - db
    environment:
      GIT_SHA: 3f4371014ccb4e99f6db8b86e7fd6afcac0f80c9
      DB_PASSWORD: password
      DB_URL: jdbc:mysql://db/OunDeDeDB
      DB_USRNAME: admin
      JWT_SECRET: <<$JWT_SECRET>>
      # disabled when production
      CORS_CONFIG_PROPERTIES_ALLOWED_ORIGINS: "*"
    # CORS_CONFIG_PROPERTIES_ALLOWED_ORIGINS: "http://cdtphuhoi.com,https://cdtphuhoi.com"
    # SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:1.24.0
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - srv
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/oun-de-de-srv.cloud/fullchain.pem:/etc/letsencrypt/live/oun-de-de-srv.cloud/fullchain.pem:ro
      - /etc/letsencrypt/live/oun-de-de-srv.cloud/privkey.pem:/etc/letsencrypt/live/oun-de-de-srv.cloud/privkey.pem:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
   mysql_data: